---
apiVersion: v1
kind: Pod
metadata:
  name: keystone
  labels:
    name: keystone
spec:
  containers:
    - name: keystone
      image: docker.io/tripleomaster/centos-binary-keystone:current-tripleo
      imagePullPolicy: IfNotPresent
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keystone-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: KEYSTONE_DB_USER
          value: keystone
        - name: KEYSTONE_DB_NAME
          value: keystone
        - name: KEYSTONE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keystone-secrets
              key: KEYSTONE_DB_PASSWORD
        - name: KEYSTONE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keystone-secrets
              key: KEYSTONE_ADMIN_PASSWORD
        - name: KEYSTONE_PUBLIC_URL
          valueFrom:
            configMapKeyRef:
              name: keystone-vars
              key: KEYSTONE_PUBLIC_URL
      ports:
        - containerPort: 5000
          protocol: TCP
      volumeMounts:
        - mountPath: /etc/keystone
          name: keystone-rw
        - mountPath: /etc/keystone-ro
          name: keystone-ro
        - mountPath: /etc/httpd-ro
          name: httpd-ro
        - mountPath: /etc/httpd
          name: httpd-rw
        - mountPath: /etc/keystone-templates
          name: keystone-templates
        - mountPath: /data
          name: data
      command:
        - /bin/sh
        - /etc/keystone-templates/startup.sh
  volumes:
    - name: keystone-rw
      emptyDir: {}
    - name: keystone-ro
      configMap:
        name: keystone-config
    - name: data
      emptyDir: {}
    - name: keystone-templates
      configMap:
        name: keystone-templates
    - name: httpd-ro
      configMap:
        name: httpd-config
    - name: httpd-rw
      emptyDir: {}
